package edu.poly.common;
// enum kiểu liệt kê
public enum PageType {
	
	USER_MANAGEMRNT_PAGE, REPORT_MANAGEMENT_PAGE, VIDEO_MANAGEMENT_PAGE,
	USER_HOME_PAGE, USER_LOGIN_PAGE, USER_REGISTRATION_PAGE, USER_CHANGE_PW, 
	USER_EDIT_PROFILE, USER_FORGOT_PASSWORD,USER_VIDEO_DETAIL, USER_FAVORITE_PAGE, USER_SHARE_PAGE 
}
